version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=img
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432"
  web:
    restart: always
    build: .
    command: bash -c "python manage.py makemigrations imagedowloader &&python manage.py migrate imagedowloader && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
